name: WebDev

services:
  frontend:
      container_name: frontend
      build:
        context: Frontend/.
        dockerfile: Dockerfile
      expose:
        - "3000"
  backend:
      container_name: backend
      build: 
        context: Backend/.
        dockerfile: Dockerfile
      expose:
        - "8080" # http
        - "8081" # https
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro